In [1]:
from Models import Model
from Metrics import compute_metrics
import pandas as pd
import numpy as np

In [2]:
heart = pd.read_csv('https://www.dropbox.com/s/jpnyx41u7wpa41m/heart_attack_clean.csv?dl=1')
heart_X = heart.drop(columns=['output'])
heart_X['B0'] = 1
heart_X = heart_X[['B0'] + list(heart_X.drop(columns='B0').columns)]
heart_X = heart_X.to_numpy()
heart_Y = heart['output'].to_numpy()

**Test Logistic**

In [3]:
logistic = Model('Logistic')
logistic.fit(heart_X, heart_Y, etas=[.01], show_iter=False)

In [4]:
logistic.coef_

array([ 0.43049373, -0.24494049, -0.35145458, -0.30755228,  0.80157621,
        1.32409691, -0.89360318, -1.44110098,  0.80462346,  0.59638294,
        0.47058831,  0.14408393,  0.48099673, -0.19458693])

In [7]:
compute_metrics(logistic.predict(heart_X), heart_Y)

Accuracy: 0.799; Precision: 0.801; Recall: 0.829; f1: 0.815; ROC-AUC: 0.796


**Test Logistic Lasso**

In [9]:
logistic_lasso = Model('Logistic Lasso', lamb=1)
logistic_lasso.fit(heart_X, heart_Y)

Eta: 0.1; Iterations: 75000
Eta: 0.01; Iterations: 75000
Eta: 0.001; Iterations: 75000
Gradient converged w/ 1999 iterations and eta = 0.0001


In [11]:
logistic_lasso.coef_

array([ 0.51786504, -0.24378054, -0.32628711, -0.28039243,  0.75477116,
        1.11543986, -0.79737482, -1.33575536,  0.5307092 ,  0.57387384,
        0.14963736,  0.00987222,  0.35943055, -0.25103774])

In [13]:
compute_metrics(logistic_lasso.predict(heart_X), heart_Y)

Accuracy: 0.802; Precision: 0.799; Recall: 0.842; f1: 0.82; ROC-AUC: 0.799


**Test SVC**

In [14]:
svc = Model('SVC', lamb=1)
svc.fit(heart_X, heart_Y)

Eta: 0.1; Iterations: 1206
Gradient converged w/ 123 iterations and eta = 0.01


In [16]:
compute_metrics(svc.predict(heart_X), heart_Y)

Accuracy: 0.736; Precision: 0.768; Recall: 0.726; f1: 0.746; ROC-AUC: 0.737


**Test LDA**

In [4]:
lda = Model('LDA')
lda.fit(heart_X, heart_Y)
lda.coef_

(array([-0.22330363, -0.31878649, -0.24470013,  0.7353733 ,  7.5546875 ,
         6.1640625 , -1.96484375,  0.98828125,  0.77734375,  0.58984375,
         2.625     ,  3.1875    ,  2.0625    ]),
 8.796416881801354)

In [6]:
compute_metrics(lda.predict(heart_X), heart_Y)

Accuracy: 0.78; Precision: 0.803; Recall: 0.781; f1: 0.792; ROC-AUC: 0.78
